###无条件
POST localhost:8080/projects
Content-Type: application/json

{
  "page": 9,
  "size": 30
}

###只有开始条件
POST localhost:8080/projects
Content-Type: application/json

{
  "page": 1,
  "size": 30,
  "startTime": "2021-05-26 00:00:00"
}

###查时间范围
POST localhost:8080/projects
Content-Type: application/json

{
  "page": 1,
  "size": 10,
  "startTime": "2021-05-26 00:00:00",
  "endTime": "2022-05-29 00:00:00"
}

###只有结束时间
POST localhost:8080/projects
Content-Type: application/json

{
  "page": 1,
  "size": 30,
  "endTime": "2022-05-29 00:00:00"
}

###只有产品类型
POST localhost:8080/projects
Content-Type: application/json

{
  "page": 1,
  "size": 30,
  "productType": 2

}

###只有阶段
POST localhost:8080/projects
Content-Type: application/json

{
  "page": 1,
  "size": 30,
  "upgradedProjectStage": "高度意向"
}

###多条件
POST localhost:8080/projects
Content-Type: application/json

{
  "page": 1,
  "size": 10,
  "startTime": "2021-05-26 00:00:00",
  "endTime": "2022-05-29 00:00:00",
  "upgradedProjectStage": "高度意向",
  "productType": 2

}


###求和
POST localhost:8080/sum
Content-Type: application/json

{
  "page": 1,
  "size": 10,
  "startTime": "2021-05-26 00:00:00",
  "endTime": "2022-05-29 00:00:00"

}

###求和
POST localhost:8080/sum
Content-Type: application/json

{
  "page": 1,
  "size": 2,
  "startTime": "2021-05-26 00:00:00",
  "endTime": "2022-05-29 00:00:00",
  "productType": 2,
  "upgradedProjectStage": "高度意向"
}