POST localhost:8080/projects
Content-Type: application/json

{
  "page": 1,
  "size": 30,
  "startTime": "2021-05-26",
  "endTime": "2021-05-29",
  "productType": 2,
  "upgradedProjectStage": "高度意向"
}